ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "social_media" JSONB DEFAULT '{}';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "forum_handles" JSONB DEFAULT '{}';
ALTER TABLE "items" ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'USD';
ALTER TABLE "items" ADD COLUMN IF NOT EXISTS "proof_of_purchase" JSONB DEFAULT '[]';
ALTER TABLE "wishlist_items" ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'USD';